### ISSUE TITLE
About results

### ISSUE THREAD

**Issue by callmelaoyi** [kamiLight/CADepth-master#1]
Thank you for your brilliant research! I have a question about the results.
The home page provided higher results than I tested myself using official weights.
Running command I used is 
`python evaluate_depth.py --load_weights_folder M_640x192 --data_path /kitti_path --eval_mono --eval_split eigen` 
But the results is 
**abs_rel |   sq_rel |     rmse | rmse_log |       a1 |       a2 |       a3 | 
&   0.106  &   0.789  &   4.580  &   0.182  &   0.890  &   0.964  &   0.983  \\**
I want to know the reason for the poor results I tested.

**Comment by kamiLight** [comment]
Due to different combinations of some libraries / packages versions, the results will be slightly different.
Here are the results tested on my experimental environment, as same as the results in paper and home page.
![2022-03-23_150052](https://user-images.githubusercontent.com/46705365/159645767-128a5950-3cde-4851-b262-c1c7010eb4fd.png)
Some version information of my experimental environment are shown, you could obtain closer results by reproducing the environment.
```
numpy==1.17.0
albumentations
opencv-python==3.4.7.28
albumentations==0.5.2
pytorch=1.7.0 
torchvision==0.8.1
python==3.7.8
CUDA==11.4
```

**Comment by callmelaoyi** [comment]
Thank you very much
